### ISSUE TITLE
Support for Dockerfile in a subfolder

### ISSUE THREAD

**Issue by stamptime** [aptible/aptible-deploy-action#31]
I am using a **monorepo** setup where each service (e.g., admin and api) has its own Dockerfile located in a subfolder. Currently, aptible-deploy-action does not seem to support specifying the location of these Dockerfiles, and **assumes they are in the root of the project.**

https://www.aptible.com/docs/core-concepts/apps/deploying-apps/image/deploying-with-git/overview#dockerfile

> To build your Dockerfile on Aptible, the file must be named Dockerfile, and located at the root of your repository.

### **Project looks like this:**

```
/project-root
  ├── /admin
  │   ├── Dockerfile
  │   └── other files...
  └── /api
      ├── Dockerfile
      └── other files...
```

I would like to be able to reference the correct Dockerfile for each service from its subfolder.

### **Proposed Solution**
Add a new input parameter to aptible-deploy-action that allows specifying the path to the Dockerfile in a subfolder. This could be an optional parameter like:

```
- name: Deploy to Aptible
  uses: aptible/aptible-deploy-action@v1
  with:
    aptible-app-id: ${{ secrets.APTIBLE_APP_ID }}
    aptible-token: ${{ secrets.APTIBLE_TOKEN }}
    dockerfile: ./admin/Dockerfile  # <-- New option to specify Dockerfile location
```
