### ISSUE TITLE
sample code to get this running?

### ISSUE THREAD

**Issue by nekapoor** [aptible/aptible-deploy-action#8]
hey all, 

we're trying to set this up to send open PRs to our staging environment but not sure how to get the branch in question as a docker image to send to staging. Is that possible using this aptible deploy action? 

Thanks!

**Comment by robertfairhead** [comment]
To generate the docker image, we suggest you use https://github.com/docker/build-push-action and then use this action for a direct docker image deployment to an existing application.

Here's one possible configuration, assuming you have set the appropriate secrets in GitHub. There are many variations on this for your individual needs, and we haven't used this for the pull request case before. So, this probably isn't perfect and you will probably have to experiment some with it.

```
name: Deploy Pull Requests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
         uses: actions/checkout@v2

      - name: Build and push Docker images
         uses: docker/build-push-action@v1
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: myorg/myrepository
           tag_with_sha: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - uses: aptible/aptible-deploy-action@v1
        with:
          username: ${{secrets.APTIBLE_ACCOUNT_USERNAME}}
          password: ${{secrets.APTIBLE_ACCOUNT_PASSWORD}}
          app: 'my-app-name'
          environment: 'my-environment-name'
          docker_img: ${{format('myorg/myrepo:{0}', github.sha)}}
```
